apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
spec:
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http  
      protocol: TCP
      port: {{ .Values.frontend.service.port }} 
      targetPort: {{ .Values.frontend.service.targetPort }}   
  type: {{ .Values.frontend.service.type }}   
    